<a href="https://colab.research.google.com/github/lovvmg/personal-project/blob/main/exercise_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A",'B','C'], index=['x','y','z'])

df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

bisa upload by file github, ini link dari raw filenya

In [ ]:
import pandas as pd

coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [67]:
coffee = coffee.reset_index(drop=True) # Reset the index to a default integer index
coffee.loc[[0,1], 'Units Sold'] = np.nan # Now, integer-based indexing with .loc will work
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso         NaN   3.99
1      Monday       Latte         NaN   5.99
2     Tuesday    Espresso        30.0   3.99
3     Tuesday       Latte        20.0   5.99
4   Wednesday    Espresso        35.0   3.99
5   Wednesday       Latte        25.0   5.99
6    Thursday    Espresso        40.0   3.99
7    Thursday       Latte        30.0   5.99
8      Friday    Espresso        45.0   3.99
9      Friday       Latte        35.0   5.99
10   Saturday    Espresso        45.0   3.99
11   Saturday       Latte        35.0   5.99
12     Sunday    Espresso        45.0   3.99
13     Sunday       Latte        35.0   5.99

In [69]:
coffee.isna().sum() # cari yang nan tuh ada berapa and dimanaa
coffee[coffee['Units Sold'].isna()]

      Day Coffee Type  Units Sold  price
0  Monday    Espresso         NaN   3.99
1  Monday       Latte         NaN   5.99

add columns

In [ ]:
import numpy as np
coffee['price']= 4.99

coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso',3.99,5.99) # kalo espresso harganya 3.99, lainnya 5.99
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

add and remove columns

In [ ]:
#rename
coffee = coffee.rename(columns={'new_price':'price'})
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   3.99
1      Monday       Latte          15   5.99
2     Tuesday    Espresso          30   3.99
3     Tuesday       Latte          20   5.99
4   Wednesday    Espresso          35   3.99
5   Wednesday       Latte          25   5.99
6    Thursday    Espresso          40   3.99
7    Thursday       Latte          30   5.99
8      Friday    Espresso          45   3.99
9      Friday       Latte          35   5.99
10   Saturday    Espresso          45   3.99
11   Saturday       Latte          35   5.99
12     Sunday    Espresso          45   3.99
13     Sunday       Latte          35   5.99

In [ ]:
coffee.tail(5)

         Day Coffee Type  Units Sold  price
9     Friday       Latte          35   5.99
10  Saturday    Espresso          45   3.99
11  Saturday       Latte          35   5.99
12    Sunday    Espresso          45   3.99
13    Sunday       Latte          35   5.99

In [ ]:
coffee.sample(3, random_state=42)  #biar ga berubah2

         Day Coffee Type  Units Sold  price
9     Friday       Latte          35   5.99
11  Saturday       Latte          35   5.99
0     Monday    Espresso          25   3.99

In [ ]:
# name_variable.loc(row, columns), bagian columnsnya diisi pakai labelnya

coffee.loc[0:5, ['Coffee Type','Units Sold']]

  Coffee Type  Units Sold
0    Espresso          25
1       Latte          15
2    Espresso          30
3       Latte          20
4    Espresso          35
5       Latte          25

In [ ]:
#name_variable.iloc(row, columns), bagian columnsnya oakai index juga, jadi index semua
coffee.iloc[1:4,0:2]

       Day Coffee Type
1   Monday       Latte
2  Tuesday    Espresso
3  Tuesday       Latte

In [ ]:
# hitung berdasarkan hari
coffee.index = coffee["Day"]
coffee.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold  price
Day
Monday        Monday    Espresso          25   3.99
Monday        Monday       Latte          15   5.99
Tuesday      Tuesday    Espresso          30   3.99
Tuesday      Tuesday       Latte          20   5.99
Wednesday  Wednesday    Espresso          35   3.99
Wednesday  Wednesday       Latte          25   5.99

ambil nilai espresso aja trus mau liat units sold by day

In [ ]:
coffee.index = coffee["Coffee Type"]
coffee.loc["Espresso",['Day','Units Sold']]

                   Day  Units Sold
Coffee Type
Espresso        Monday          25
Espresso       Tuesday          30
Espresso     Wednesday          35
Espresso      Thursday          40
Espresso        Friday          45
Espresso      Saturday          45
Espresso        Sunday          45

sorted

In [ ]:
coffee.sort_values("Units Sold") #, ascending= [False] ( ini membalikkan jadi dari besar ke kecil)

                   Day Coffee Type  Units Sold  price
Coffee Type
Latte           Monday       Latte          15   5.99
Latte          Tuesday       Latte          20   5.99
Espresso        Monday    Espresso          25   3.99
Latte        Wednesday       Latte          25   5.99
Espresso       Tuesday    Espresso          30   3.99
Latte         Thursday       Latte          30   5.99
Espresso     Wednesday    Espresso          35   3.99
Latte           Friday       Latte          35   5.99
Latte           Sunday       Latte          35   5.99
Latte         Saturday       Latte          35   5.99
Espresso      Thursday    Espresso          40   3.99
Espresso        Friday    Espresso          45   3.99
Espresso      Saturday    Espresso          45   3.99
Espresso        Sunday    Espresso          45   3.99

In [ ]:
for index, row in coffee.iterrows():
  print(index)
  print(row)
  print("\n")

Espresso
Day              Monday
Coffee Type    Espresso
Units Sold           25
price              3.99
Name: Espresso, dtype: object


Latte
Day            Monday
Coffee Type     Latte
Units Sold         15
price            5.99
Name: Latte, dtype: object


Espresso
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
price              3.99
Name: Espresso, dtype: object


Latte
Day            Tuesday
Coffee Type      Latte
Units Sold          20
price             5.99
Name: Latte, dtype: object


Espresso
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
price               3.99
Name: Espresso, dtype: object


Latte
Day            Wednesday
Coffee Type        Latte
Units Sold            25
price               5.99
Name: Latte, dtype: object


Espresso
Day            Thursday
Coffee Type    Espresso
Units Sold           40
price              3.99
Name: Espresso, dtype: object


Latte
Day            Thursday
Coffee Type       Latte
Units Sold           30
price              5.99
Name: Latte, dtype: object


Espresso
Day              Friday
Coffee Type    Espresso
Units Sold           45
price              3.99
Name: Espresso, dtype: object


Latte
Day            Friday
Coffee Type     Latte
Units Sold         35
price            5.99
Name: Latte, dtype: object


Espresso
Day            Saturday
Coffee Type    Espresso
Units Sold           45
price              3.99
Name: Espresso, dtype: object


Latte
Day            Saturday
Coffee Type       Latte
Units Sold           35
price              5.99
Name: Latte, dtype: object


Espresso
Day              Sunday
Coffee Type    Espresso
Units Sold           45
price              3.99
Name: Espresso, dtype: object


Latte
Day            Sunday
Coffee Type     Latte
Units Sold         35
price            5.99
Name: Latte, dtype: object

In [ ]:
result = pd.read_parquet('results.parquet')
result.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

filtering + sorted

nama.loc[kondisi, mau tampilin apa aja].sort(by apaa)

In [48]:
bios = pd.read_excel('olympics_data.xlsx',sheet_name="bios") # ambil file excel yang sheet bios
bios.loc[bios['height_cm'] > 220, ['name','height_cm']].sort_values("height_cm") # filter yang heightnya lebih dari 220 trus tampilin nama + heightnya lanjut di sorting based on heightnya juga

                   name  height_cm
5673     Gunther Behnke      221.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0

multiple filtering + sorting

In [49]:
bios.loc[(bios['height_cm'] > 210) & (bios['born_country']=='USA'),['name','height_cm','born_country']].sort_values("name")

                      name  height_cm born_country
118573     Al-Farouq Aminu      211.0          USA
112319         Chris Kaman      213.0          USA
6442    Christian Laettner      211.0          USA
7012       Daniel Santiago      213.0          USA
6281        Darrall Imhoff      211.0          USA
6937        David Robinson      216.0          USA
133332      DeAndre Jordan      211.0          USA
132188    Domantas Sabonis      211.0          USA
112366       Dwight Howard      211.0          USA
143712        JaVale McGee      213.0          USA
142044       Jahlil Okafor      211.0          USA
6379            Joe Kleine      211.0          USA
6393            Jon Koncak      213.0          USA
6106       Marc Freiberger      211.0          USA
5894            Mel Counts      213.0          USA
142930          Mike Tobey      213.0          USA
6722      Shaquille O'Neal      216.0          USA
6615          Tom McMillen      212.0          USA
5781        Tommy Burleson      223.0          USA
123850      Tyson Chandler      216.0          USA
5681          Walt Bellamy      211.0          USA

find with some character. can also combine with '&'

In [50]:
bios[bios['name'].str.contains("Keith|patrick", case=False)] # case false buat ignore kapital, ini cari yang ada unsur keith or patrick

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

also can use query function, lebih simple

In [89]:
bios.query('born_country == "USA"') # ambil yang dari USA aja

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Average
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Average
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Short
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Tall
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Average
...,...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN,Tall
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN,Tall
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN,Tall
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN,Tall
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN,Tall

In [51]:
bios.query('born_country == "USA" and born_city== "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

tampilkan kalo dia dari USA and then tampilin name, born country, born region, lalu sorted it by name

In [52]:
bios.loc[bios['born_country']== "USA",['name','born_region','born_country']].sort_values('name')

                      name     born_region born_country
11224       Almighty Voice        New York          USA
137756            Angelina      New Jersey          USA
19849         Islah-ud-Din        New York          USA
87300             A J Kitt        New York          USA
143485         A'ja Wilson  South Carolina          USA
...                    ...             ...          ...
144660           Zoe Atkin   Massachusetts          USA
145429         Zoe Kalapos        Michigan          USA
88843        Éric LeMarque      California          USA
119534        Óscar Molina      California          USA
129287  Şebnem Kimyacıoğlu      California          USA

[9641 rows x 3 columns]

In [53]:
bios_new = bios.copy()
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0] # ambil unsur pertama di namanya

bios_new.query('first_name == "Keith"') #ambil nama yg ada keith-nya

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

ambil bagian tahunnya aja

In [54]:
bios_new = bios.copy()
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

SAVING TO FILE

In [55]:
bios_new.to_csv('bios_new.csv', index=False)

add category pakai lambda function
bisa juga pake funciton biasa,
apply(nama_function, axis=)
axis = 0 columns;
axis = 1 row

In [56]:
bios['height_category']= bios['height_cm'].apply(lambda x: 'Short' if x < 168 else('Average' if x < 186 else 'Tall'))
bios[['name','height_cm','height_category']]

                         name  height_cm height_category
0       Jean-François Blanchy        NaN            Tall
1              Arnaud Boetsch      183.0         Average
2                Jean Borotra      183.0         Average
3             Jacques Brugnon      168.0         Average
4                Albert Canet        NaN            Tall
...                       ...        ...             ...
145495      Polina Luchnikova      167.0           Short
145496    Valeriya Merkusheva      168.0         Average
145497        Yuliya Smirnova      163.0           Short
145498         André Foussard      166.0           Short
145499          Bill Phillips        NaN            Tall

[145500 rows x 3 columns]

In [57]:
nocs = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/noc_regions.csv')

In [58]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC',how='left')

In [59]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Short,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Short,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,AUS,Australia,NaN

gabung 2 (atas -bawah) yang USA di atas yang GBR di bawah

In [62]:
usa = bios[bios['born_country']=="USA"].copy()
gbr = bios[bios['born_country']=="GBR"].copy()

new_df = pd.concat([usa,gbr])
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Tall
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Tall
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,Average
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Tall
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Tall

aggregating data

In [70]:
bios['born_country'].value_counts()

born_country
USA       9641
GER       6891
GBR       5792
FRA       5143
ITA       4709
          ...
SEY          1
SMT          1
COK          1
Corfu        1
Aarhus       1
Name: count, Length: 236, dtype: int64

In [71]:
bios[bios['born_country']=="USA"]['born_city'].value_counts()

born_city
New York         416
Chicago          283
Los Angeles      230
Philadelphia     205
Boston           153
                ...
Milpitas           1
Chesterfield       1
American Fork      1
Cadyville          1
Fair Haven         1
Name: count, Length: 2255, dtype: int64

In [78]:
import pandas as pd
coffee = coffee.fillna(coffee['Units Sold'].mean()) # isi yang nan pakek rata2 units sold
coffee.groupby(['Coffee Type'])['Units Sold'].sum() # cari tahu jumlah unit sold based on coffee types

Coffee Type
Espresso    275.0
Latte       215.0
Name: Units Sold, dtype: float64

In [79]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price':'sum'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday           45.0   3.99
            Monday           35.0   3.99
            Saturday         45.0   3.99
            Sunday           45.0   3.99
            Thursday         40.0   3.99
            Tuesday          30.0   3.99
            Wednesday        35.0   3.99
Latte       Friday           35.0   5.99
            Monday           35.0   5.99
            Saturday         35.0   5.99
            Sunday           35.0   5.99
            Thursday         30.0   5.99
            Tuesday          20.0   5.99
            Wednesday        25.0   5.99

In [80]:
coffee['Revenue'] = coffee['Units Sold'] * coffee['price']
coffee

          Day Coffee Type  Units Sold  price  Revenue
0      Monday    Espresso        35.0   3.99   139.65
1      Monday       Latte        35.0   5.99   209.65
2     Tuesday    Espresso        30.0   3.99   119.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [85]:
pivot = coffee.pivot(columns='Coffee Type', index='Day',values='Revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday         139.65  209.65
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75